"""
STEP 4 (SNOMED Updated): Querying the Reasoned Knowledge Graph
==============================================================
The automated HermiT reasoner (via owlready2) has already executed
our clinical logic and saved the results into merged_reasoned.owl.

Now, we just use simple SPARQL to read the conclusions using
canonical SNOMED CT Identifiers (sct:).
"""

from rdflib import Graph, Namespace
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "output"
ONTOLOGY_FILE = DATA_DIR / "merged_reasoned.owl"

# Namespaces (we query via SNOMED, ignorant of the hospital schemas!)
SCT = Namespace("http://snomed.info/id/")
EHR = Namespace("http://hospital-a.org/ehr#")
CLIN = Namespace("http://hospital-b.org/clinical#")

def run_queries():
    g = Graph()
    print(f"Loading {ONTOLOGY_FILE.name}...")
    g.parse(str(ONTOLOGY_FILE), format="xml")
    g.bind("sct", SCT)
    g.bind("ehr", EHR)
    g.bind("clin", CLIN)
    
    # ─────────────────────────────────────────────────────────────
    # QUERY 1: Find patients with Bleeding Risk (Warfarin + Grapefruit)
    # The Reasoner automatically assigned these patients to a new class based on rules!
    # We don't query the drugs anymore, we just query the output class.
    # ─────────────────────────────────────────────────────────────
    q1 = """
    PREFIX sct: <http://snomed.info/id/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    
    SELECT ?patient WHERE {
        # sct:BleedingRiskPatient is the intersection class generated by the reasoner
        ?patient rdf:type <http://snomed.info/id/BleedingRiskPatient> .
    }
    """
    print("\n" + "="*60)
    print("QUERY 1: Identifying Patients with Severe Bleeding Risks")
    print("         (Automatically inferred by HermiT reasoner)")
    print("="*60)
    
    found1 = False
    for row in g.query(q1):
        found1 = True
        patient_uri = str(row.patient).split('#')[-1]
        print(f" 🚨 [ALERT] High Bleeding Risk Detected: {patient_uri}")
    
    if not found1: print("  ✓ No bleeding risk patients found.")

    # ─────────────────────────────────────────────────────────────
    # QUERY 2: Find all patients with ANY form of Diabetes
    # Hospital A calls it "DiabetesType2", Hospital B calls it "E11".
    # We query the SNOMED SCTID 73211009.
    # ─────────────────────────────────────────────────────────────
    q2 = """
    PREFIX sct: <http://snomed.info/id/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX ehr: <http://hospital-a.org/ehr#>
    PREFIX clin: <http://hospital-b.org/clinical#>
    
    SELECT DISTINCT ?patient WHERE {
        { ?patient ehr:hasCondition ?disease } UNION { ?patient clin:hasDiagnosis ?disease }
        ?disease rdf:type sct:73211009 .
    }
    """
    print("\n" + "="*60)
    print("QUERY 2: Find all Diabetics (Cross-Hospital SNOMED Lookup)")
    print("         (sct:73211009 = Diabetes mellitus)")
    print("="*60)
    
    found2 = False
    for row in g.query(q2):
        found2 = True
        patient_uri = str(row.patient).split('#')[-1]
        print(f"  ⚕️ Patient {patient_uri} has Diabetes.")
        
    if not found2: print("  No diabetic patients found.")

    print("\n" + "="*60)
    print("✅ Queries completed.")

if __name__ == "__main__":
    run_queries()
